project:
  output-dir: _output
  type: book

book:
  title : "Report - Variational Sparse Coding"
  chapters:
    - index.qmd
    - autoencoder.qmd
    - vae.qmd
    - vsc.qmd
    - experiments.qmd
    - conclusion.qmd
  downloads: [pdf]
  repo-url: https://github.com/your-username/your-repo-namehttps://github.com/Ophiase/VSC-For-Sparse-VAE

format:
  html:
    theme: cosmos
    # cosmos, darkly, sandstone, sketchy
    toc: true
    number-sections: true
  pdf:
    theme: cosmo
    title: "Report_VSC"
    toc: true